name: lint & test

on:
  pull_request:
    paths:
      - 'packages/**'
      - '!packages/**.md'

jobs:
  cov-designer:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: install
        run: npm i && npm run setup:skip-build

      - name: echo
        run: echo ${{ toJSON(github) }}